// Generated by uniffi-bindgen-react-native
import { TurboModuleRegistry } from 'react-native';
import type { TurboModule } from 'react-native';

export interface Spec extends TurboModule {
  installRustCrate(): void;
}

export default TurboModuleRegistry.getEnforcing<Spec>(
  'ReactNativeLibsignal'
);
