// Generated by uniffi-bindgen-react-native
module.exports = {
  dependency: {
    platforms: {
      android: {
        componentDescriptors: [],
        cmakeListsPath: '../cpp/CMakeLists.txt',
      },
    },
  },
};
